INSERT INTO `members` (`id`, `first_name`, `last_name`, `username`, `password`, `email`, `role`, `campusid_ref`) VALUES
(54, 'BATH', 'CD', 'cdbath', 'wHYl8TUB', 'info@studytours.it', 'course_director', 4),
(55, 'BEDFORD', 'CD', 'cdbedford', 'xWSwg7hl', 'info@studytours.it', 'course_director', 2),
(56, 'BOSTON', 'CD', 'cdboston', 'DBiLriNl', 'info@studytours.it', 'course_director', 33),
(57, 'CAMBRIDGE', 'CD', 'cdcambridge', 'a6X3wDSV', 'info@studytours.it', 'course_director', 19),
(58, 'CANTERBURY', 'CD', 'cdcanterbury', 'bTuwPAEc', 'info@studytours.it', 'course_director', 6),
(59, 'CHELMSFORD', 'CD', 'cdchelmsford', 'n7OHvG6W', 'info@studytours.it', 'course_director', 41),
(60, 'CHELTENHAM', 'CD', 'cdcheltenham', 'x3kI8rDf', 'info@studytours.it', 'course_director', 15),
(61, 'CHESTER', 'CD', 'cdchester', 'dtsCzmdL', 'info@studytours.it', 'course_director', 20),
(62, 'CHICAGO', 'CD', 'cdchicago', 'pUZ3Gv6a', 'info@studytours.it', 'course_director', 55),
(63, 'DUBLIN', 'CD', 'cddublin', 'G5uPMXlf', 'info@studytours.it', 'course_director', 36),
(64, 'DUBLIN DCU', 'CD', 'cddublindcu', 'Wdq0N1Ka', 'info@studytours.it', 'course_director', 39),
(65, 'EDINBURGH', 'CD', 'cdedinburgh', 'gL3rA86f', 'info@studytours.it', 'course_director', 21),
(66, 'EFFINGHAM', 'CD', 'cdeffingham', 'BDqqEPYP', 'info@studytours.it', 'course_director', 52),
(67, 'GALWAY', 'CD', 'cdgalway', 'cH9Ysl8L', 'info@studytours.it', 'course_director', 54),
(68, 'LEICESTER', 'CD', 'cdleicester', '8cliSzXA', 'info@studytours.it', 'course_director', 13),
(69, 'LIVERPOOL', 'CD', 'cdliverpool', '0WD1yDSt', 'info@studytours.it', 'course_director', 47),
(70, 'LONDON', 'CD', 'cdlondon', 'igEIPO7K', 'info@studytours.it', 'course_director', 48),
(71, 'LONDON CAMDEN', 'CD', 'cdlondoncamden', 'NP0WXzhI', 'info@studytours.it', 'course_director', 44),
(72, 'LONDON GREENWICH', 'CD', 'cdlondongreenwich', 'bBMUyDzk', 'info@studytours.it', 'course_director', 3),
(73, 'LONDON MEDWAY', 'CD', 'cdlondonmedway', 'bWRqxllv', 'info@studytours.it', 'course_director', 7),
(74, 'LONDON ROEHAMPTON', 'CD', 'cdlondonroehampton', 'nyCiKTdy', 'info@studytours.it', 'course_director', 14),
(75, 'LONDON TOOTING', 'CD', 'cdlondontooting', 'Urb3V3Al', 'info@studytours.it', 'course_director', 43),
(76, 'LONDON TWICKENHAM', 'CD', 'cdlondontwickenham', '9Se15iHK', 'info@studytours.it', 'course_director', 45),
(77, 'LONDON UCL', 'CD', 'cdlondonucl', 'ChuHrWDn', 'info@studytours.it', 'course_director', 49),
(78, 'LOS ANGELES', 'CD', 'cdlosangeles', 'xgGl3DDG', 'info@studytours.it', 'course_director', 30),
(79, 'LOUGHBOROUGH', 'CD', 'cdloughborough', 'MlgOhnZY', 'info@studytours.it', 'course_director', 12),
(80, 'MALTA VILLAGE', 'CD', 'cdmaltavillage', 'kB7gGENQ', 'info@studytours.it', 'course_director', 38),
(81, 'MALTA VILLAGE 3', 'CD', 'cdmaltavillage3', 'upjfe7zn', 'info@studytours.it', 'course_director', 50),
(82, 'MALTA VILLAGE 4S', 'CD', 'cdmaltavillage4s', 'QiC34RN8', 'info@studytours.it', 'course_director', 51),
(83, 'MIAMI', 'CD', 'cdmiami', 'TeXgYh8S', 'info@studytours.it', 'course_director', 46),
(84, 'NEW YORK FELICIAN', 'CD', 'cdnewyorkfelician', 'awwhSTI9', 'info@studytours.it', 'course_director', 42),
(85, 'NEW YORK RIDER', 'CD', 'cdnewyorkrider', 'VhkFmN1d', 'info@studytours.it', 'course_director', 27),
(86, 'NORWICH', 'CD', 'cdnorwich', 'AgT4hIS4', 'info@studytours.it', 'course_director', 5),
(87, 'NY - DREW UNIVERSITY', 'CD', 'cdnydrewuniversity', 'ujzkbsD8', 'info@studytours.it', 'course_director', 28),
(88, 'ORLANDO', 'CD', 'cdorlando', 'F3spOULq', 'info@studytours.it', 'course_director', 32),
(89, 'PLYMOUTH', 'CD', 'cdplymouth', 'VJPKM7hD', 'info@studytours.it', 'course_director', 24),
(90, 'PORTSMOUTH', 'CD', 'cdportsmouth', 'eNkn8yPX', 'info@studytours.it', 'course_director', 23),
(91, 'SAN FRANCISCO', 'CD', 'cdsanfrancisco', 'r8ETBZ6W', 'info@studytours.it', 'course_director', 31),
(92, 'ST ANDREWS', 'CD', 'cdstandrews', 'gHSaKbQZ', 'info@studytours.it', 'course_director', 26),
(93, 'WINDSOR', 'CD', 'cdwindsor', 'dVGpNCt8', 'info@studytours.it', 'course_director', 53);